baseURL = "/schwartz/"
locale = "zh-tw"
theme = "PaperMod"

[frontmatter]
date = ["date", "publishDate", "lastmod"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首頁"
    url = "/"
    weight = 5

  [[menu.main]]
    identifier = "schwartz"
    name = "外科學"
    url = "/schwartz/"
    weight = 10

  [[menu.main]]
    identifier = "search"
    name = "搜尋"
    url = "/schwartz/search/"
    weight = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "index"
  isPlainText = true
